name: studyx
description: 'My personal school study app.'
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.2.8
  cupertino_icons: ^1.0.8
  flutter_settings_ui: ^3.0.0
  provider: ^5.0.0
  syncfusion_flutter_calendar: ^27.1.55
  shared_preferences: ^2.3.2
  animated_theme_switcher: ^2.0.10
  syncfusion_flutter_datepicker: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
