name: 'Check and Build'

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4.2.2

    - uses: actions/setup-java@v4.5.0
      with:
        java-version: '17'
        distribution: oracle

    - uses: subosito/flutter-action@v2.14.0
      with:
        channel: 'stable'
        cache: true

    - run: flutter pub get

    - run: flutter analyze

    - run: flutter test

    - run: flutter build apk

    - uses: actions/upload-artifact@v4.4.3
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
